name: Build

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  dist-and-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    name: dists & docs (${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build distributions
        run: |
          poetry build

      - name: Install package
        run: |
          poetry install --extras "docs speed"

      - name: Build docs
        shell: bash
        run: |
          cd docs
          poetry run sphinx-build -b html -j auto -a . _build/html
          # Doesn't allow missing references
          # sphinx-build -b html -j auto -a -n -T -W --keep-going . _build/html
